### ISSUE TITLE
Application letter: Seggan

### ISSUE THREAD

**Issue by Seggan** [Slimefun-Addon-Community/Community-Center#1]
## :clipboard: Tell us a bit about yourself!
An amateur coder, a developer of more addons than anyone except TheBusyBiscuit

## :question: Why do you want to join this community?
So I can collaborate with others

## :bulb: What do you expect from other members?
Help in writing code, specifically designing machines

## :flashlight: What can other members expect from you?
Coding the technical stuff (math, recipes, modules)

## :card_index_dividers: Which projects do you want to work or collaborate on?
Doing SlimeChem with @Mooy1

## :link: Your Slimefun addons (with links)
[SFCalc](https://github.com/Seggan/SFCalc), [Slimy Power Suits](https://github.com/Seggan/Slimy-Power-Suits), [Liquid](https://github.com/Seggan/Liquid), [SlimefunWarfare](https://github.com/Seggan/SlimefunWarfare), also collabing on [SlimeChem](https://github.com/Mooy1/SlimeChem)

## :headphones: Discord username (optional)
Seggan#8111

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome :heart:
