### ISSUE TITLE
Application letter: SentryoZ

### ISSUE THREAD

**Issue by SentryoZ** [Slimefun-Addon-Community/Community-Center#10]
## :clipboard: Tell us a bit about yourself!

I am the web dev using php, using minecraft to learn java.

## :question: Why do you want to join this community?

I join this community because i see i can learn very much knowlegde of java

## :bulb: What do you expect from other members?

Someone can help me to solve problem about java

## :flashlight: What can other members expect from you?

A lot of bugs to fix? idk :))

## :link: Your Slimefun addons (with links)

https://github.com/SentryoZ/DisguiseCookies

## :headphones: Discord username (optional)

SentryoZ#5429

**Comment by TheBusyBiscuit** [comment]
Why was this closed?

Also, never heard of that addon, why is it not listed on the wiki?

**Comment by SentryoZ** [comment]
i made this addon for learning, and i think it isn't good enough for use on server

**Comment by TheBusyBiscuit** [comment]
I originally made Slimefun for learning too, in fact it was my first Java project ever and look where we are today :)
I am sure there would be tons of people who would enjoy this to play with. After all, you might get some feedback which will help you learn even more and improve your skills.

I looked at your addon too. And I can tell you: I have seen and also written much worse code, it's looking good thus far.
You don't have to publicly list your addon of course but you shouldn't think it would be "not good enough" for that.

**Comment by SentryoZ** [comment]
Thank you so much, you made my day :smile: . I'm going to reopen this.

**Comment by TheBusyBiscuit** [comment]
Welcome to the team! :) I sent you an invite to join.
Note though that the organization is still in its setup stage, so you won't find too much resources just yet.
There is also a new discord server being created right now, it's all still very early on but it's always good to see people being interested in becoming a part of this community.
