### ISSUE TITLE
Application letter: GallowsDove

### ISSUE THREAD

**Issue by GallowsDove** [Slimefun-Addon-Community/Community-Center#11]
## :clipboard: Tell us a bit about yourself!

High-school student, entering a university following year. Love computer science, and everything related.

## :question: Why do you want to join this community?

Hoping to expand my knowledge, as well as learn more, while contributing to a community that I want to support.

## :bulb: What do you expect from other members?

Just general advice, and engagement with an actual practical project.

## :flashlight: What can other members expect from you?

I'm not really experienced, but I'll try to be as active as possible, so whatever might be required.

## :card_index_dividers: Which projects do you want to work or collaborate on?

No idea yet.

## :link: Your Slimefun addons (with links)

https://github.com/GallowsDove/FoxyMachines

## :headphones: Discord username (optional)

Thezerix#9071

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
