### ISSUE TITLE
Application letter: Apeiros-46B

### ISSUE THREAD

**Issue by Apeiros-46B** [Slimefun-Addon-Community/Community-Center#15]
## :clipboard: Tell us a bit about yourself!
I'm Apeiros, and I recently started learning java through minecraft as a hobby.

## :question: Why do you want to join this community?
I would like to join this community to work with others and learn more about java.

## :bulb: What do you expect from other members?
I dont really expect much from others except to treat me with kindness, thats all.

## :flashlight: What can other members expect from you?
Same as above

## :card_index_dividers: Which projects do you want to work or collaborate on?
I'm interested in creating or collaborating on an addon that bridges the gap between technology and magic.

## :link: Your Slimefun addons (with links)
Released: https://github.com/Apeiros-46B/AlchimiaVitae
In development: N/A
Currently stalled/Planning to re-do: https://github.com/Apeiros-46B/MagicXpansion 

## :headphones: Discord username (optional)
Apeiros#6754

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.

**Comment by jigglypuff2731** [comment]
cool
