### ISSUE TITLE
Application letter: TerslenK

### ISSUE THREAD

**Issue by TerslenK** [Slimefun-Addon-Community/Community-Center#17]
## :clipboard: Tell us a bit about yourself!
ehhh
a st00pid newbie in java

## :question: Why do you want to join this community?
dunno maybe i could get better help here

## :bulb: What do you expect from other members?
¯\_(ツ)_/¯

## :flashlight: What can other members expect from you?
¯\_(ツ)_/¯

## :card_index_dividers: Which projects do you want to work or collaborate on?
i just wanna finish my first addon

## :link: Your Slimefun addons (with links)
https://github.com/TerslenK/Ex-Limus not finished yet

## :headphones: Discord username (optional)
TerslenK

**Comment by TheBusyBiscuit** [comment]
Sorry, but you will have to fill out the application letter properly...
Can't even fill in your own username or discord tag correctly. *smh*

**Comment by TerslenK** [comment]
ouch

**Comment by TerslenK** [comment]
then im gonna fill it again when i finish this addon
