### ISSUE TITLE
Application letter: lucasGithuber

### ISSUE THREAD

**Issue by lucasGithuber** [Slimefun-Addon-Community/Community-Center#18]
## :clipboard: Tell us a bit about yourself!
im just a newbie in addon programming

## :question: Why do you want to join this community?
i think i will have better help here (not that #programming-help isnt enough 😳 )

## :bulb: What do you expect from other members?
help when needed

## :flashlight: What can other members expect from you?
¯\_(ツ)_/¯

## :card_index_dividers: Which projects do you want to work or collaborate on?
my addon, and if i can, other addons from other people

## :link: Your Slimefun addons (with links)
(unfinished)      https://github.com/lucasGithuber/RandomExpansion 

## :headphones: Discord username (optional)
OOOOMAGAAA#4507

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
