### ISSUE TITLE
Application letter: Char

### ISSUE THREAD

**Issue by char3210** [Slimefun-Addon-Community/Community-Center#19]
## :clipboard: Tell us a bit about yourself!

Hi I write stuff related to Minecraft occasionally, mostly in Java.

## :question: Why do you want to join this community?

i want to help with the development of Slimefun addons to make the playing experience better, and also get involved with the community as they are very friendly.

## :bulb: What do you expect from other members?

To be helpful and open-minded

## :flashlight: What can other members expect from you?

I will try to be helpful to others as well and also accept others' thoughts

## :card_index_dividers: Which projects do you want to work or collaborate on?

Whatever interests me, so probably a variety of projects

## :link: Your Slimefun addons (with links)

[SlimefunAdvancements](https://github.com/qwertyuioplkjhgfd/SlimefunAdvancements)
working on another addon that is currently private and unfinished

## :headphones: Discord username (optional)

Char#5513

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
