### ISSUE TITLE
Application letter: Mooy1

### ISSUE THREAD

**Issue by Mooy1** [Slimefun-Addon-Community/Community-Center#2]
## :clipboard: Tell us a bit about yourself!
bad coder, started learning java 2ish months ago

## :question: Why do you want to join this community?
Looks cool, id like to help out with anyones project if they need help.

## :bulb: What do you expect from other members?
Nothing really xD

## :flashlight: What can other members expect from you?
I can help em out a bit, code quality not guaranteed

## :card_index_dividers: Which projects do you want to work or collaborate on?
SlimeChem with @Seggan for now

## :link: Your Slimefun addons (with links)

Released: https://github.com/Mooy1/InfinityExpansion 
In dev: https://github.com/Mooy1/SlimeQuest  https://github.com/Mooy1/SlimeChem 

## :headphones: Discord username (optional)
Riley#5911

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome :heart:
