### ISSUE TITLE
Application letter: NickCoder

### ISSUE THREAD

**Issue by MrNickCoder** [Slimefun-Addon-Community/Community-Center#20]
## :clipboard: Tell us a bit about yourself!

Hi, I'm NickCoder, and i like coding and solving logical problems as a hobby. I only know the basics of java and python, but i can mostly solve logical problem efficiently.
I'm not really good at speaking English.

## :question: Why do you want to join this community?

I started to learn about slimefun and wanted to create my own addon. I also want to improve and suggest things to other addon developer.

## :bulb: What do you expect from other members?

I'm not really expecting them to help me. Its just i want other members to treat me with kindness.

## :flashlight: What can other members expect from you?

They can expect me to help them with their problems, especially if it is logical problem. I will also treat them kindly.

## :card_index_dividers: Which projects do you want to work or collaborate on?

I'm currently working on my Unfinished Addon(Paradoxium), and making a seperate library for convenience.
I also want to help or collaborating a addon that makes the game more or like a Medieval RPG theme where they fight with magic and weapons like CrystamaeHistoria.

## :link: Your Slimefun addons (with links)

[Paradoxium](https://github.com/MrNickCoder/Paradoxium) (WIP)

## :headphones: Discord username (optional)

NickCoder#1827

**Comment by FN-FAL113** [comment]
![image](https://user-images.githubusercontent.com/88238718/159917901-650ed614-bff1-42de-9072-23a0cedfaaf0.png)
not sure about this but reviewers can make their judgement upon this application
