### ISSUE TITLE
Application letter: TheRealEzCoins

### ISSUE THREAD

**Issue by iae-st** [Slimefun-Addon-Community/Community-Center#21]
## :clipboard: Tell us a bit about yourself!
Hello, I'm an aspiring add-on developer, who's just trying to learn more about plugins and Java in general!
I've been coding addons for about 3-4 months now.

## :question: Why do you want to join this community?
I think this would be a great place to learn more about Slimefun and Java itself since there are some very talented addon creators here.

## :bulb: What do you expect from other members?
Not all that much, just hoping to get help when needed since I'm still relatively new to Slimefun addon creation.

## :flashlight: What can other members expect from you?
I'm a very talkative person, and will try my best to help where I can

## :card_index_dividers: Which projects do you want to work or collaborate on?
I would want to work on anything really! (Might need some guidance sometimes tho)

## :link: Your Slimefun addons (with links)
MiniBlocks - https://github.com/TheRealEzCoins/MiniBlocks 
(2 other addons which are currently private)

## :headphones: Discord username (optional)
Ez#1000

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
