### ISSUE TITLE
Application letter: ybw0014

### ISSUE THREAD

**Issue by ybw0014** [Slimefun-Addon-Community/Community-Center#23]
## :clipboard: Tell us a bit about yourself!

I'm ybw0014, and my Chinese nickname in English is Guizhan. I like making Minecraft plugins.

## :question: Why do you want to join this community?

I would like to exchange ideas about addons, also l want to learn more.

## :bulb: What do you expect from other members?

Suggestions or advice.

## :flashlight: What can other members expect from you?

My suggestions or advice, ~~maybe useful experiences~~.

## :card_index_dividers: Which projects do you want to work or collaborate on?

No idea yet.

## :link: Your Slimefun addons (with links)

https://github.com/SlimefunGuguProject/Bump
https://github.com/GuizhanCraft/GuizhanCraft

## :headphones: Discord username (optional)

ybw0014#2209

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
