### ISSUE TITLE
Application letter: FN-FAL113

### ISSUE THREAD

**Issue by FN-FAL113** [Slimefun-Addon-Community/Community-Center#24]
## :clipboard: Tell us a bit about yourself!
Hello I'm FN_FAL113, a college student who went in a journey in exploring spigot plugins development

## :question: Why do you want to join this community?
I'm a huge fan of other addon devs, they inspired me so I hope to inspire others.

## :bulb: What do you expect from other members?
Hospitality and kindness

## :flashlight: What can other members expect from you?
Ideas and any queries that I can at most respond

## :card_index_dividers: Which projects do you want to work or collaborate on?
Nothing yet but hopefully soon 

## :link: Your Slimefun addons (with links)
https://github.com/FN-FAL113/FN-FAL-s-Amplifications
https://github.com/FN-FAL113/SfChunkInfo

## :headphones: Discord username (optional)
FN_FAL#7779

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
