### ISSUE TITLE
Application letter: JasperChaseTOQ

### ISSUE THREAD

**Issue by JasperChaseTOQ** [Slimefun-Addon-Community/Community-Center#25]
## :clipboard: Tell us a bit about yourself!

hi im japserchasetoq and ive recently started developing my own addon

## :question: Why do you want to join this community?

i want to join this community cause i love slimefun and i want to contribute to it

## :bulb: What do you expect from other members?

helpful advice and guidance 

## :flashlight: What can other members expect from you?

helpful advice and guidance 

## :card_index_dividers: Which projects do you want to work or collaborate on?

im willing to work on anything and everything ( where im able to help out that is im still learning)

## :link: Your Slimefun addons (with links)

Builder's kit https://github.com/JasperChaseTOQ/CompressionCraft

## :headphones: Discord username (optional)

JasperChaseTOQ#5105

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
