### ISSUE TITLE
Application letter: SchnTgaiSpock

### ISSUE THREAD

**Issue by SchnTgaiSpock** [Slimefun-Addon-Community/Community-Center#26]
## :clipboard: Tell us a bit about yourself!
Hello, I'm SchnTgaiSpock, and I mainly write in python and js. I got into addon dev (and java) during this years addon jam.

## :question: Why do you want to join this community?
I enjoy playing Slimefun, and I would like to contribute to the community

## :bulb: What do you expect from other members?
To give advice, tips, etc...

## :flashlight: What can other members expect from you?
Same as above, giving advice, tips, etc...

## :card_index_dividers: Which projects do you want to work or collaborate on?
Mostly my own addons, but I'm still open to collaborate

## :link: Your Slimefun addons (with links)
Wildernether: [https://github.com/SchnTgaiSpock/Wildernether](https://github.com/SchnTgaiSpock/Wildernether)

## :headphones: Discord username (optional)
Schn#2085

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
