### ISSUE TITLE
Application letter: JustAHuman_xD

### ISSUE THREAD

**Issue by JustAHuman-xD** [Slimefun-Addon-Community/Community-Center#28]
## :clipboard: Tell us a bit about yourself!

I enjoy playing minecraft especially modded and slimefun! I also have a love of programming and have been learning java for the past couple of months, leading to the creation and release of my addon!

## :question: Why do you want to join this community?

To be able to better collaborate and talk to other people who share the same interests!

## :bulb: What do you expect from other members?

Collaboration Ideas, maybe ideas, tips etc

## :flashlight: What can other members expect from you?

Same thing that I expect from them ^

## :card_index_dividers: Which projects do you want to work or collaborate on?

My own addons but would love to collaborate on other addons! Including helping maintain addons like Infinity Expansion. (I already have a PR open for InfinityLib)

## :link: Your Slimefun addons (with links)

SpiritsUnchained: https://github.com/JustAHuman-xD/SpiritsUnchained

## :headphones: Discord username (optional)

JustAHuman#8583

**Comment by TheBusyBiscuit** [comment]
Welcome! :heart:
I have sent you an invite.
