### ISSUE TITLE
Application letter: RelativoBR

### ISSUE THREAD

**Issue by RelativoBR** [Slimefun-Addon-Community/Community-Center#29]
## :clipboard: Tell us a bit about yourself!
Developer for over 14 years, working with several languages including Java. Currently going through several personal and professional changes, which does not allow me to work on hobby projects.

## :question: Why do you want to join this community?
A long time ago I created a private addon (Supreme) that I made public a few years ago, but I would like to pass it on to the community, thus allowing greater community interaction, and also so that I can help and other projects in the future.

## :bulb: What do you expect from other members?
I'm not expecting anything very relevant, maybe some ideas on how to improve the code that already exists.

## :flashlight: What can other members expect from you?
Which helps to resolve bugs and help with the maintenance update of existing plugins.

## :card_index_dividers: Which projects do you want to work or collaborate on?
Supreme that I hope to transfer

## :link: Your Slimefun addons (with links)
[Supreme](https://github.com/RelativoBR/Supreme)

## :headphones: Discord username (optional)
RelativoBR

**Comment by WalshyDev** [comment]
Welcome! Sent the invite :)
