### ISSUE TITLE
Application letter: NCBPFluffyBear

### ISSUE THREAD

**Issue by NCBPFluffyBear** [Slimefun-Addon-Community/Community-Center#3]
## :clipboard: Tell us a bit about yourself!
Hi, I'm FluffyBear, and I recently picked up coding and created FluffyMachines. I'm going to college next year, and I want to keep coding as a side hobby!

## :question: Why do you want to join this community?
This looks like a cool new concept with a lot of benefits and features. I'm totally down for collaboration with other addon devs. Also, teams 👀 

## :bulb: What do you expect from other members?
Be helpful and respectful. I've learned loads of stuff from #programming-help and Bukkit/Spigot forums, and I expect the manner to be somewhat similar here.

## :flashlight: What can other members expect from you?
I've been known for discovering bugs here and there due to being an persistent tester. I'm still improving my coding, but I test every bit of my code to make sure bad stuff doesn't make it past me. Other than that, I'll do my best to help others out.

## :card_index_dividers: Which projects do you want to work or collaborate on?
Pretty much anything I have the time for. I currently have my eyes on a TC port for Spigot.

## :link: Your Slimefun addons (with links)
[FluffyMachines](https://github.com/NCBPFluffyBear/FluffyMachines)

## :headphones: Discord username (optional)
FluffyBear#9133

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome :heart:
