### ISSUE TITLE
Application letter: PranavVerma-droid

### ISSUE THREAD

**Issue by PranavVerma-droid** [Slimefun-Addon-Community/Community-Center#30]
## :clipboard: Tell us a bit about yourself!

I am a Student, that is Really Passionate about Programming. <br>
Over my Years, I have learnt many Programming Languages Such as **Java, Python, C, etc**.

## :question: Why do you want to join this community?
I just wanted to help and be a part of this growing community, and, wanted to give back and help develop a lot of  the popular addons, and, someday, even Slimefun Plugin Itself.

## :bulb: What do you expect from other members?
I do expect other people to help me with any issues I have with my Addon.
That would be Really Nice.

## :flashlight: What can other members expect from you?
As long as I have _adequate_ knowledge about a certain thing, I will always be willing to give back, and support other members in that particular thing, if they ever need help.

## :card_index_dividers: Which projects do you want to work or collaborate on?

I obviously wanted to work on My Own Addon, [AdvancedTech](https://github.com/PranavVerma-droid/AdvancedTech) and, I would also like to work on other community addons, like, Galactifun.

## :link: Your Slimefun addons (with links)

I have Made My Own Addon Named [AdvancedTech](https://github.com/PranavVerma-droid/AdvancedTech).

## :headphones: Discord username (optional)

envitixy_xd (New Format Username)

**Comment by TheBusyBiscuit** [comment]
Welcome! ❤️
I have sent you an invite.

**Comment by PranavVerma-droid** [comment]
Thank you!
