### ISSUE TITLE
Application letter: VoperAD

### ISSUE THREAD

**Issue by VoperAD** [Slimefun-Addon-Community/Community-Center#31]
## :clipboard: Tell us a bit about yourself!

Hi, I'm Voper and I'm currently studying Computer Engineering. I don't have much professional experience (if any at all), but in my spare time I enjoy coding and studying various subjects, one of which is Minecraft plugin development.

## :question: Why do you want to join this community?

Well, I think that being part of a community can help us in a lot of ways. We can learn from each other and discuss ideas. Also, I love to play Slimefun even though I don't play as much as before, so it would be great to be part of this community.

## :bulb: What do you expect from other members?

They have already helped me a lot in the #programming-help channel XD. I expect to learn even more with them and give back to the community.

## :flashlight: What can other members expect from you?

I'm respectful with anyone and I could help them with anything within my reach. 

## :card_index_dividers: Which projects do you want to work or collaborate on?

There isn't a specific project in my mind, but I could collaborate on anything as long as I have time to. Solving bugs or maybe adding new recipes or improving the code (I'm not the best option in the last case XD).

## :link: Your Slimefun addons (with links)

<a href="https://github.com/VoperAD/SlimeFrame">SlimeFrame</a>

## :headphones: Discord username (optional)

_voper

**Comment by WalshyDev** [comment]
Welcome!
I have sent you an invite :)
