### ISSUE TITLE
Application letter: J3fftw1

### ISSUE THREAD

**Issue by J3fftw1** [Slimefun-Addon-Community/Community-Center#4]
## :clipboard: Tell us a bit about yourself!

I'm j3fftw1 known as Panda. You guys probably know me already.
I made the best Slimefun Addon together with @Walshydev called LiteXpansion also with his help i created SoundMuffler. 
I have been part of the Slimefun community for a while now. Slimefun made me start programming.

## :question: Why do you want to join this community?

I want to join this community to help people with there addons and help me with mine. We can also talk about how to do things in the best way. Or make some kind of knowledge base for some stuff like how to create textures for heads.

## :bulb: What do you expect from other members?

I dont expect anything from them.

## :flashlight: What can other members expect from you?

Help with stuff were possible. Help test new stuff. Bring in tips. Anything i can do tbh when there is the time for it

## :card_index_dividers: Which projects do you want to work or collaborate on?

My own addons and others not specifically any 

## :link: Your Slimefun addons (with links)

https://github.com/J3fftw1/LiteXpansion
https://github.com/J3fftw1/SoundMuffler

## :headphones: Discord username (optional)

Panda.com#0806

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome :heart:
