### ISSUE TITLE
Application letter: Sfiguz7

### ISSUE THREAD

**Issue by Sfiguz7** [Slimefun-Addon-Community/Community-Center#5]
## :clipboard: Tell us a bit about yourself!

I'm Sfiguz7 but most know me as the blueberry, italian Math guy or simply Alessio. I am a moderator on Slimefun's Discord. I like writing walls of text and overdetailing answers but for this once I'll save you from my own wrath :P Oh and I also love Math as you may have gotten from the above!

## :question: Why do you want to join this community?

The idea that stands behind the community is very enticing: helping each other, easier collaborations, a more tightly knit developing group (even though we happily mess with each other already). There are benefits for the individual of course but the accrued value of all the interactions is by far the thing that interests the most.

## :bulb: What do you expect from other members?

A joint agreement on bullying the blob of course! Jokes aside, I foresee a lot more interaction: people hot-fixing or simply cleaning up each others' projects, bug testing, more teaming up allowing for bigger and better Addons to come. I don't expect anything in particular from people except the usual mutual respect that should be fundamental in any relationship and I'm sure they'll live up to my expectations.

## :flashlight: What can other members expect from you?

Lots of Italian cursing at non working code and sub par implementations may be on the list :D I'm also known for being decently helpful when it comes to my beloved Math so on top of the general aid in testing and fixing I may be a good asset to the community when it comes to that.

## :card_index_dividers: Which projects do you want to work or collaborate on?

I have no particular interest at the moment, I don't like tunnel visioning and would prefer being open to any offer. Of course I have to juggle free time between my work as a Dev, real life and my other projects (I'm not only a Dev and not only for Slimefun as some know) so I may turn down some of them but we're all on the same boat, if you need anything asking me is always worth a shot!

## :link: Your Slimefun addons (with links)

TranscEndence: https://github.com/Sfiguz7/TranscEndence
ExtraTools: https://github.com/Sfiguz7/ExtraTools
Tinkers (WIP, private)

## :headphones: Discord username (optional)

Sfiguz7#7063

EDIT: grammar

**Comment by WalshyDev** [comment]
> A joint agreement on bullying the blob of course! 

Denied for bullying me

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome :heart:
