### ISSUE TITLE
Application letter: poma123

### ISSUE THREAD

**Issue by poma123** [Slimefun-Addon-Community/Community-Center#6]
## :clipboard: Tell us a bit about yourself!

Hey,

I am poma123 and you probably know me from the Slimefun Discord server where I joined back in June. My first goal was to push some bug fixes and implement some of the ideas that came up in the suggestions channel. I've made several PRs containing API extensions and other things. My most enjoyable PR was a typo fix PR, I laughed a lot! _(winks at Cookie)_

Time went on, and now it is an honour to be part of the Slimefun GitHub organization. and reviewing code when I have a little time (much less lately :/). I've also had my first Hacktoberfest this year, and I really enjoyed it.

Throughout this short but wealthy journey, I've learned how to write code better and create well-documented APIs.
I've created my first official Slimefun addon named 'GlobalWarming' which was inspired by one of Walshy's suggestions.
Although it looks great, climate change is a real issue. Anyway, I'm not going to write a book about global warming, especially not here, on GitHub. _(As I am an addon developer now, it would be great if one of you gave me the Addon Developer role on Discord :((( plss. EDIT: Thank you yellow jello <3)_

Lastly, I really like this addon-community idea. I can certainly say that the SF community has grown into a HUGE group of worthy people, who should collaborate in order to create mind-blowing projects together. We could someday play some game together as well, like continue the building of Alessio's and my plot on VoidRealms, or go to Hypixel, or play some other games instead.

## :question: Why do you want to join this community?

As I stated before, this is a caring community with worthy people. Who on Earth doesn't wanna join a community like this? What is this question?? But let's get serious! I've tried to help anyone who had trouble and asked for help on Discord. Also, I really love the funny side of this community, the yellow jello is our beloved MEAN SHUSHER, who finally has broadband.

## :bulb: What do you expect from other members?

Patience, help, fun and kindness. Everyone should be kind to each other, and nothing wrong could happen!
We could as well create teams, work together on different projects, get help from each other.

## :flashlight: What can other members expect from you?

I am here to help. I love open-source, people can create wonderful things together. This could make bug fixes and code reviewing faster. I want to collaborate with you, help you, create something new from scratch. I really like to make API classes and document them, so if you need help with anything, I'm here, and I can say that we are all here if needed.

## :card_index_dividers: Which projects do you want to work or collaborate on?

Hmm, I don't really know. As I've contributed to Cookie's EcoPower addon, I would definitely help him or fix issues in that project. Also, 1.17 is coming. A rewrite would be needed for my GlobalWarming addon, to be up to date with the new vanilla temperature system, and implement some other weather mechanics (e.g. thunderstorms or other cool things?).

## :link: Your Slimefun addons (with links)

[GlobalWarming](https://github.com/poma123/GlobalWarming)
[EcoPower](https://github.com/TheBusyBiscuit/EcoPower) (in collaboration with Cookie)
## :headphones: Discord username (optional)

poma_123#2795

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome :heart:
