### ISSUE TITLE
Application letter: svr333

### ISSUE THREAD

**Issue by svr333** [Slimefun-Addon-Community/Community-Center#8]
## :clipboard: Tell us a bit about yourself!
Im svr333 aka Senne, 18yo guy from Belgium (Flemish, aka fake Dutch). My main language is C# but Im looking to expand towards others and Java is one of those.

## :question: Why do you want to join this community?
I don't have any intention on making any addon (though Ive been looking to revive an old one but I dont think I will bring it back, due to time shortage) but I would love to join to see and aid others on their addons by either reviewing or PRing fixes/features.
Slimefun is something Ive enjoyed playing over the last few years and coding for this is something fun to do and Im able to learn Java while doing so.

## :bulb: What do you expect from other members?
Kindness and quality memes :)

## :flashlight: What can other members expect from you?
The same

## :card_index_dividers: Which projects do you want to work or collaborate on?
Nothing really specific, but I'm always down to review or implement a thing or two every now and then.

## :headphones: Discord username (optional)
svr333#3451

**Comment by svr333** [comment]
No I did not forget to change the title

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome ❤️
