### ISSUE TITLE
Application letter: ProfElements

### ISSUE THREAD

**Issue by ProfElements** [Slimefun-Addon-Community/Community-Center#9]
## :clipboard: Tell us a bit about yourself!

Im ProfElements, I like making things. My main language is Golang, I just started java not to long ago. I used my addon to learn it.

## :question: Why do you want to join this community?

I want to be able to help and get helped with addons, I also want to be able to figure out general java concepts as I help. I also want to make more addons that are more community focussed and overall modular addons.

## :bulb: What do you expect from other members?

Try to be helpful and respectful. I also hope to have good conversation with the others

## :flashlight: What can other members expect from you?

Same as above. Be helpful and respectful and try to make good conversation

## :card_index_dividers: Which projects do you want to work or collaborate on?

I mostly want to make a Forestry-esque addon.

## :link: Your Slimefun addons (with links)

DynaTech : https;//github.com/profelements/dynatech

## :headphones: Discord username (optional)

ProfElements#6358

**Comment by TheBusyBiscuit** [comment]
Accepted :)
Welcome ❤️
